### ISSUE TITLE
[Docs] API docs not rendering on docs site

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#215] opened 2021-08-17 22:08 UTC
The api documentations [page](https://dask-sql.readthedocs.io/en/latest/pages/api.html) returns a blank page on the docs site.

**Comment by nils-braun** [comment] 2021-08-18 06:18
Thanks @ayushdg - there seems to be a bug in the sphinx build process.
Until it's fixes, please have a look into [an older version](https://dask-sql.readthedocs.io/en/0.3.6/pages/api.html).

**Comment by nils-braun** [comment] 2021-08-18 10:36
The problem is fixed now and the [API docs](https://dask-sql.readthedocs.io/en/latest/pages/api.html) are visible again. There was a dependency missing during the sphinx build process.
Why I did not receive a mail due to the failed build from readthedocs I do not know so far...

**Closed by nils-braun** 2021-08-18 10:36 UTC

**Comment by ayushdg** [comment] 2021-08-18 15:09
Thanks @nils-braun for the quick response and fix!
